[profile.default]
solc = "0.8.25"
allow_internal_expect_revert = true
script_execution_protection = false
optimizer_runs = 1000000
bytecode_hash = "none"
show_progress = true
allow_paths = [
  # pnpm symlinks to the project root's node_modules
  "../../node_modules",
  # template uses linked mud packages from within the mud monorepo
  "../../../../packages",
  # projects created from this template and using linked mud packages
  "../../../mud/packages",
]
extra_output_files = [
  "abi",
  "evm.bytecode"
]
fs_permissions = [{ access = "read", path = "./"}]

[fuzz]
runs = 1000
depth = 250

[invariant]
shrink_run_limit = 4294967295

[profile.odyssey]
eth_rpc_url = "https://odyssey.ithaca.xyz"
