name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.6.0

      - name: Install dependencies
        run: pnpm install

      - name: Test contracts
        working-directory: packages/contracts
        run: pnpm test
        env:
          FORCE_DETERMINISTIC_TIMESTAMP: true #  To ensure reproducible invariant failures.

